apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "assistant-host.name" . }}
  labels: {{- include "assistant-host.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels: {{- include "assistant-host.labels" . | nindent 6 }}
