import type { ValidationDiagnostic, ValidationLevel } from './dashboardModel';
import { sha256Hex } from './hash';
import { lezerParser, promqlProbe, type PromqlParser } from './promqlCheck';
import type { WorkspaceResourceMeta, WorkspaceResourceSnapshot } from './types';

export const ALERT_RULE_API_GROUP = 'rules.alerting.grafana.app';
export const ALERT_RULE_API_VERSION = `${ALERT_RULE_API_GROUP}/v0alpha1`;
export const FOLDER_ANNOTATION = 'grafana.app/folder';
/** Rule group labels on AlertRule metadata (grafana/apps/alerting/rules/pkg/apis/alerting/v0alpha1/ext.go). */
export const GROUP_LABEL = 'grafana.com/group';
export const GROUP_INDEX_LABEL = 'grafana.com/group-index';
export const PROVENANCE_ANNOTATION = 'grafana.com/provenance';
const MANAGED_BY_ANNOTATION = 'grafana.app/managedBy';
const MAX_TITLE_LENGTH = 190;
/** Grafana's default scheduler tick; evaluation intervals must be a multiple of it. */
const BASE_INTERVAL_SECONDS = 10;
const EXPRESSION_DATASOURCE = '__expr__';
const NO_DATA_STATES = ['NoData', 'Ok', 'Alerting', 'KeepLast'];
const EXEC_ERR_STATES = ['Error', 'Ok', 'Alerting', 'KeepLast'];
/** ngmodels.LabelsUserCannotSpecify */
const RESERVED_LABELS = new Set([
  '__grafana_autogenerated__',
  '__grafana_receiver__',
  '__grafana_route_settings_hash__',
]);

type AnyRecord = Record<string, any>;

/** Contact points, time intervals, and routing trees that notification settings may reference. */
export type AlertNotificationTargets = { receivers: string[]; timeIntervals: string[]; routingTrees: string[] };

export type AlertRuleValidationReport = {
  schemaVersion: 1;
  ok: boolean;
  levels: Record<ValidationLevel, 'passed' | 'failed' | 'skipped'>;
  promqlParser?: PromqlParser['name'];
  errors: ValidationDiagnostic[];
  warnings: ValidationDiagnostic[];
  notRun: string[];
};

/**
 * Converts an AlertRule from Grafana's App Platform API into the editable working copy:
 * apiVersion, kind, metadata.name, the folder annotation, and spec. Group membership,
 * provenance, and the other provider-owned metadata stay in meta.json and are merged back
 * when the rule is written.
 */
export function toAlertRuleSnapshot(
  resource: AnyRecord,
  options: { url?: string; folderTitle?: string } = {}
): WorkspaceResourceSnapshot {
  const metadata: AnyRecord = resource.metadata ?? {};
  const annotations: Record<string, string> = metadata.annotations ?? {};
  const labels: Record<string, string> = metadata.labels ?? {};
  const uid = String(metadata.name ?? '');
  const folderUid = annotations[FOLDER_ANNOTATION] || undefined;
  const document = {
    apiVersion: resource.apiVersion || ALERT_RULE_API_VERSION,
    kind: 'AlertRule',
    metadata: { name: uid, ...(folderUid ? { annotations: { [FOLDER_ANNOTATION]: folderUid } } : {}) },
    spec: resource.spec ?? {},
  };
  const content = `${JSON.stringify(document, null, 2)}\n`;
  const provenance = annotations[PROVENANCE_ANNOTATION];
  const manager = annotations[MANAGED_BY_ANNOTATION];
  const groupIndex = Number(labels[GROUP_INDEX_LABEL]);
  const meta: WorkspaceResourceMeta = {
    kind: 'alertRule',
    uid,
    apiVersion: String(document.apiVersion),
    namespace: metadata.namespace,
    resourceVersion: metadata.resourceVersion,
    title: typeof resource.spec?.title === 'string' ? resource.spec.title : undefined,
    folderUid,
    url: options.url,
    managedBy: provenance ? `provisioning (provenance ${provenance})` : manager || undefined,
    ...(labels[GROUP_LABEL] ? { group: labels[GROUP_LABEL] } : {}),
    ...(labels[GROUP_LABEL] && Number.isFinite(groupIndex) ? { groupIndex } : {}),
    preconditions: 'client',
    fetchedAt: new Date().toISOString(),
    annotations,
    labels,
    contentHash: sha256Hex(content),
  };
  return { content, meta };
}

/**
 * The request body for a write: the working copy's spec and folder, plus the provider-owned
 * metadata (group labels, provenance and other annotations) of the rule as it is stored now.
 * New rules get neither: Grafana rejects group labels on create and puts the rule in no group.
 */
export function alertRuleWriteBody(document: AnyRecord, current?: AnyRecord) {
  const folder = document.metadata?.annotations?.[FOLDER_ANNOTATION];
  const annotations: Record<string, string> = { ...(current?.metadata?.annotations ?? {}) };
  if (folder) {
    annotations[FOLDER_ANNOTATION] = folder;
  }
  const labels: Record<string, string> = { ...(current?.metadata?.labels ?? {}) };
  if (folder && labels[FOLDER_ANNOTATION]) {
    labels[FOLDER_ANNOTATION] = folder;
  }
  return {
    apiVersion: ALERT_RULE_API_VERSION,
    kind: 'AlertRule',
    metadata: {
      name: document.metadata?.name,
      ...(current?.metadata?.resourceVersion ? { resourceVersion: current.metadata.resourceVersion } : {}),
      annotations,
      ...(Object.keys(labels).length ? { labels } : {}),
    },
    spec: document.spec,
  };
}

/** One line of /grafana/catalog/alert-rules.ndjson. */
export function alertRuleCatalogEntry(snapshot: WorkspaceResourceSnapshot, folderTitle?: string) {
  const { meta } = snapshot;
  let spec: AnyRecord = {};
  try {
    spec = JSON.parse(snapshot.content).spec ?? {};
  } catch {
    // Listed without spec details.
  }
  const link = panelLink(spec);
  return compact({
    uid: meta.uid,
    title: meta.title,
    folderUid: meta.folderUid,
    folderTitle,
    group: meta.group,
    labels: spec.labels && Object.keys(spec.labels).length ? spec.labels : undefined,
    paused: spec.paused === true ? true : undefined,
    provenance: meta.annotations?.[PROVENANCE_ANNOTATION] || undefined,
    writable: !meta.managedBy,
    dashboardUid: link?.dashboardUid,
    panelId: link?.panelId,
    path: `/grafana/alert-rules/${meta.uid}/rule.json`,
  });
}

function panelLink(spec: AnyRecord): { dashboardUid: string; panelId: number } | undefined {
  if (typeof spec.panelRef?.dashboardUID === 'string' && Number.isFinite(spec.panelRef?.panelID)) {
    return { dashboardUid: spec.panelRef.dashboardUID, panelId: spec.panelRef.panelID };
  }
  const dashboardUid = spec.annotations?.__dashboardUid__;
  const panelId = Number(spec.annotations?.__panelId__);
  return typeof dashboardUid === 'string' && dashboardUid && Number.isFinite(panelId)
    ? { dashboardUid, panelId }
    : undefined;
}

/**
 * Validates an alert rule working copy: envelope, structure (title, evaluation settings,
 * expressions and their references), PromQL syntax, notification references, the datasource
 * allow-list, and, against the fetched rule, the changes the single-rule API cannot make.
 */
export async function validateAlertRuleDocument(
  content: string,
  options: {
    expectedUid?: string;
    /** The fetched rule; its absence means the rule is created. */
    base?: WorkspaceResourceSnapshot;
    allowedDatasourceUids?: string[];
    /** Prometheus datasource UIDs, to recognize PromQL queries whose model does not name a type. */
    prometheusDatasourceUids?: string[];
    promql?: PromqlParser;
    notificationTargets?: AlertNotificationTargets;
    signal?: AbortSignal;
  } = {}
): Promise<AlertRuleValidationReport> {
  const errors: ValidationDiagnostic[] = [];
  const warnings: ValidationDiagnostic[] = [];
  const levels: AlertRuleValidationReport['levels'] = {
    json: 'skipped',
    envelope: 'skipped',
    structure: 'skipped',
    queries: 'skipped',
    policy: 'skipped',
    server: 'skipped',
  };
  const notRun = [
    'Grafana admission checks (folder existence, rule sequences, quota), run by Grafana on apply',
    'rule evaluation (run the queries with grafana-prom query)',
  ];
  if (!options.notificationTargets) {
    notRun.push('notification references (contact points, time intervals, routing trees)');
  }
  let promqlParser: PromqlParser['name'] | undefined;
  const finish = (): AlertRuleValidationReport => ({
    schemaVersion: 1,
    ok: errors.length === 0,
    levels,
    ...(promqlParser ? { promqlParser } : {}),
    errors,
    warnings,
    notRun,
  });
  const level = (name: ValidationLevel, before: number) => {
    levels[name] = errors.length > before ? 'failed' : 'passed';
  };

  let resource: unknown;
  try {
    resource = JSON.parse(content);
    levels.json = 'passed';
  } catch (error) {
    levels.json = 'failed';
    errors.push({ level: 'json', message: `invalid JSON: ${error instanceof Error ? error.message : String(error)}` });
    return finish();
  }

  // Envelope ---------------------------------------------------------------
  let before = errors.length;
  const record = isRecord(resource) ? resource : undefined;
  if (!record) {
    errors.push({ level: 'envelope', message: 'document must be a JSON object' });
    level('envelope', before);
    return finish();
  }
  if (record.apiVersion !== ALERT_RULE_API_VERSION) {
    errors.push({
      level: 'envelope',
      path: '.apiVersion',
      message: `apiVersion must be ${ALERT_RULE_API_VERSION} (got ${JSON.stringify(record.apiVersion)})`,
    });
  }
  if (record.kind !== 'AlertRule') {
    errors.push({ level: 'envelope', path: '.kind', message: 'kind must be "AlertRule"' });
  }
  const metadata = isRecord(record.metadata) ? record.metadata : undefined;
  if (typeof metadata?.name !== 'string' || !metadata.name) {
    errors.push({ level: 'envelope', path: '.metadata.name', message: 'metadata.name (the rule UID) is required' });
  } else if (options.expectedUid && metadata.name !== options.expectedUid) {
    errors.push({
      level: 'envelope',
      path: '.metadata.name',
      message: `metadata.name ${JSON.stringify(metadata.name)} must match the directory UID ${JSON.stringify(options.expectedUid)}; create a new directory to copy a rule`,
    });
  }
  const folder = metadata?.annotations?.[FOLDER_ANNOTATION];
  if (typeof folder !== 'string' || !folder) {
    errors.push({
      level: 'envelope',
      path: `.metadata.annotations["${FOLDER_ANNOTATION}"]`,
      message: 'the folder UID is required',
    });
  }
  if (metadata?.resourceVersion !== undefined) {
    warnings.push({
      level: 'envelope',
      path: '.metadata.resourceVersion',
      message: 'resourceVersion is provider-owned and ignored; the workspace applies against the fetched revision',
    });
  }
  if (isRecord(metadata?.labels) && Object.keys(metadata.labels).length > 0) {
    warnings.push({
      level: 'envelope',
      path: '.metadata.labels',
      message:
        'metadata.labels are provider-owned (rule group, folder) and ignored; alert labels belong in .spec.labels',
    });
  }
  const spec = isRecord(record.spec) ? record.spec : undefined;
  if (!spec) {
    errors.push({ level: 'envelope', path: '.spec', message: 'spec must be an object' });
  }
  level('envelope', before);
  if (!spec) {
    return finish();
  }

  // Structure --------------------------------------------------------------
  before = errors.length;
  const structure = (path: string, message: string) => errors.push({ level: 'structure', path, message });
  if (typeof spec.title !== 'string' || !spec.title.trim()) {
    structure('.spec.title', 'title is required');
  } else if (spec.title.length > MAX_TITLE_LENGTH) {
    structure('.spec.title', `title is longer than ${MAX_TITLE_LENGTH} characters`);
  }
  const interval = parseDuration(spec.trigger?.interval);
  if (interval === undefined || interval <= 0) {
    structure(
      '.spec.trigger.interval',
      `evaluation interval must be a positive duration such as "1m" (got ${JSON.stringify(spec.trigger?.interval)})`
    );
  } else if (interval % BASE_INTERVAL_SECONDS !== 0) {
    warnings.push({
      level: 'structure',
      path: '.spec.trigger.interval',
      message: `Grafana requires a multiple of the scheduler interval (${BASE_INTERVAL_SECONDS}s by default)`,
    });
  }
  for (const field of ['for', 'keepFiringFor'] as const) {
    if (spec[field] !== undefined && (parseDuration(spec[field]) ?? -1) < 0) {
      structure(`.spec.${field}`, `${field} must be a duration such as "5m" (got ${JSON.stringify(spec[field])})`);
    }
  }
  if (
    spec.missingSeriesEvalsToResolve !== undefined &&
    !(Number.isInteger(spec.missingSeriesEvalsToResolve) && spec.missingSeriesEvalsToResolve >= 0)
  ) {
    structure('.spec.missingSeriesEvalsToResolve', 'must be a non-negative integer');
  }
  if (spec.paused !== undefined && typeof spec.paused !== 'boolean') {
    structure('.spec.paused', 'paused must be true or false');
  }
  if (spec.noDataState !== undefined && !NO_DATA_STATES.includes(spec.noDataState)) {
    structure('.spec.noDataState', `noDataState must be one of ${NO_DATA_STATES.join(', ')}`);
  }
  if (spec.execErrState !== undefined && !EXEC_ERR_STATES.includes(spec.execErrState)) {
    structure('.spec.execErrState', `execErrState must be one of ${EXEC_ERR_STATES.join(', ')}`);
  }
  for (const field of ['labels', 'annotations'] as const) {
    const value = spec[field];
    if (value === undefined) {
      continue;
    }
    if (!isRecord(value) || Object.values(value).some((item) => typeof item !== 'string')) {
      structure(`.spec.${field}`, `${field} must map names to strings`);
    }
  }
  for (const key of Object.keys(isRecord(spec.labels) ? spec.labels : {})) {
    if (RESERVED_LABELS.has(key)) {
      structure(`.spec.labels["${key}"]`, 'label is reserved by Grafana');
    }
  }
  validateExpressions(spec.expressions, structure);
  if (spec.panelRef !== undefined) {
    if (
      !isRecord(spec.panelRef) ||
      typeof spec.panelRef.dashboardUID !== 'string' ||
      !Number.isInteger(spec.panelRef.panelID) ||
      spec.panelRef.panelID <= 0
    ) {
      structure('.spec.panelRef', 'panelRef needs a dashboardUID and a positive integer panelID');
    } else {
      const annotationDashboard = spec.annotations?.__dashboardUid__;
      const annotationPanel = spec.annotations?.__panelId__;
      if (
        annotationDashboard !== undefined &&
        (annotationDashboard !== spec.panelRef.dashboardUID ||
          String(annotationPanel) !== String(spec.panelRef.panelID))
      ) {
        warnings.push({
          level: 'structure',
          path: '.spec.panelRef',
          message:
            'panelRef and the __dashboardUid__/__panelId__ annotations name different panels; Grafana links the panel from the annotations',
        });
      }
    }
  }
  validateNotificationSettings(spec.notificationSettings, options.notificationTargets, structure);
  level('structure', before);

  // Queries ----------------------------------------------------------------
  before = errors.length;
  const prometheusUids = new Set(options.prometheusDatasourceUids ?? []);
  const queries: Array<{ id: string; expr: string }> = [];
  for (const [refId, expression] of Object.entries(isRecord(spec.expressions) ? spec.expressions : {})) {
    const model = isRecord(expression?.model) ? expression.model : undefined;
    const datasourceUid = expression?.datasourceUID;
    if (!model || typeof model.expr !== 'string' || !datasourceUid || datasourceUid === EXPRESSION_DATASOURCE) {
      continue;
    }
    const type = model.datasource?.type;
    if (type === 'prometheus' || (type === undefined && prometheusUids.has(datasourceUid))) {
      queries.push({ id: refId, expr: model.expr });
    } else {
      warnings.push({
        level: 'queries',
        path: `.spec.expressions.${refId}`,
        message: `not checked: no syntax parser for ${type ?? `datasource ${datasourceUid}`}`,
      });
    }
  }
  if (queries.length > 0) {
    const probes = queries.map(({ id, expr }) => ({ id, expr: promqlProbe(expr) }));
    let results;
    let parser = options.promql ?? lezerParser;
    try {
      results = await parser.parse(probes, options.signal);
    } catch (error) {
      if (options.signal?.aborted) {
        throw error;
      }
      warnings.push({
        level: 'queries',
        message: `${error instanceof Error ? error.message : String(error)}; checked with the less strict offline parser`,
      });
      parser = lezerParser;
      results = await parser.parse(probes);
    }
    promqlParser = parser.name;
    const byId = new Map(results.map((result) => [result.id, result]));
    for (const query of queries) {
      const error = byId.get(query.id)?.error;
      if (error) {
        errors.push({
          level: 'queries',
          path: `.spec.expressions.${query.id}.model.expr`,
          message: `PromQL: ${error}: ${query.expr}`,
        });
      }
    }
    level('queries', before);
  }

  // Policy -----------------------------------------------------------------
  before = errors.length;
  const policy = (message: string, path?: string) =>
    errors.push({ level: 'policy', message, ...(path ? { path } : {}) });
  const base = options.base;
  if (base?.meta.managedBy) {
    policy(`alert rule is managed by ${base.meta.managedBy} and is read-only here; change it in its source`);
  }
  if (options.allowedDatasourceUids?.length) {
    const allowed = new Set(options.allowedDatasourceUids);
    for (const [refId, expression] of Object.entries(isRecord(spec.expressions) ? spec.expressions : {})) {
      const uid = expression?.datasourceUID;
      if (uid && uid !== EXPRESSION_DATASOURCE && !allowed.has(uid)) {
        policy(`datasource UID ${JSON.stringify(uid)} is not allowed for the assistant`, `.spec.expressions.${refId}`);
      }
    }
  }
  if (base) {
    const baseDocument = safeParse(base.content);
    const baseFolder = baseDocument?.metadata?.annotations?.[FOLDER_ANNOTATION];
    if (baseFolder && folder && folder !== baseFolder) {
      policy(
        `moving a rule to another folder is not supported here (${JSON.stringify(baseFolder)} → ${JSON.stringify(folder)}); move it in Grafana's alert rule editor`,
        `.metadata.annotations["${FOLDER_ANNOTATION}"]`
      );
    }
    const baseInterval = parseDuration(baseDocument?.spec?.trigger?.interval);
    if (base.meta.group && interval !== undefined && baseInterval !== undefined && interval !== baseInterval) {
      policy(
        `the evaluation interval belongs to rule group ${JSON.stringify(base.meta.group)} and applies to all of its rules; Grafana ignores it in single-rule updates, so change the group's interval in Grafana`,
        '.spec.trigger.interval'
      );
    }
  }
  level('policy', before);
  return finish();
}

/** Checks the expression graph; returns the refIds. */
function validateExpressions(expressions: unknown, structure: (path: string, message: string) => void) {
  const refIds = new Set<string>();
  if (!isRecord(expressions) || Object.keys(expressions).length === 0) {
    structure('.spec.expressions', 'at least one expression is required');
    return refIds;
  }
  Object.keys(expressions).forEach((refId) => refIds.add(refId));
  const sources = Object.entries(expressions).filter(([, expression]) => expression?.source === true);
  if (sources.length !== 1) {
    structure(
      '.spec.expressions',
      sources.length === 0
        ? 'exactly one expression must be the alert condition ("source": true)'
        : `only one expression may be the alert condition; found ${sources.map(([refId]) => refId).join(', ')}`
    );
  }
  for (const [refId, expression] of Object.entries(expressions)) {
    const path = `.spec.expressions.${refId}`;
    if (!isRecord(expression) || !isRecord(expression.model)) {
      structure(path, 'expression needs a model object');
      continue;
    }
    const datasourceUid = expression.datasourceUID;
    const isExpression = datasourceUid === undefined || datasourceUid === EXPRESSION_DATASOURCE;
    if (!isExpression) {
      const from = parseDuration(expression.relativeTimeRange?.from);
      const to = parseDuration(expression.relativeTimeRange?.to);
      if (from === undefined || to === undefined || from <= to) {
        structure(
          `${path}.relativeTimeRange`,
          'queries need a relativeTimeRange whose "from" is further back than "to", for example {"from": "10m", "to": "0s"}'
        );
      }
      continue;
    }
    for (const ref of expressionRefs(expression.model)) {
      if (!refIds.has(ref)) {
        structure(`${path}.model`, `refers to ${JSON.stringify(ref)}, which is not an expression of this rule`);
      } else if (ref === refId) {
        structure(`${path}.model`, 'expression refers to itself');
      }
    }
  }
  return refIds;
}

/** RefIds a server-side expression reads: reduce/resample/threshold inputs, math variables, classic conditions. */
export function expressionRefs(model: AnyRecord): string[] {
  const type = model.type;
  if (type === 'math') {
    return [...String(model.expression ?? '').matchAll(/\$\{?([A-Za-z0-9_]+)\}?/g)].map((match) => match[1]);
  }
  if (type === 'classic_conditions') {
    return (Array.isArray(model.conditions) ? model.conditions : [])
      .map((condition: AnyRecord) => condition?.query?.params?.[0])
      .filter((ref: unknown): ref is string => typeof ref === 'string');
  }
  if ((type === 'reduce' || type === 'resample' || type === 'threshold') && typeof model.expression === 'string') {
    return [model.expression];
  }
  return [];
}

function validateNotificationSettings(
  settings: unknown,
  targets: AlertNotificationTargets | undefined,
  structure: (path: string, message: string) => void
) {
  if (settings === undefined || settings === null) {
    return;
  }
  const path = '.spec.notificationSettings';
  if (!isRecord(settings)) {
    structure(path, 'notificationSettings must be an object');
    return;
  }
  const type = settings.type ?? 'SimplifiedRouting';
  if (type === 'NamedRoutingTree') {
    if (typeof settings.routingTree !== 'string' || !settings.routingTree) {
      structure(`${path}.routingTree`, 'routingTree is required for NamedRoutingTree');
    } else if (targets && !targets.routingTrees.includes(settings.routingTree)) {
      structure(`${path}.routingTree`, `routing tree ${JSON.stringify(settings.routingTree)} does not exist`);
    }
    return;
  }
  if (type !== 'SimplifiedRouting') {
    structure(`${path}.type`, 'type must be SimplifiedRouting or NamedRoutingTree');
    return;
  }
  if (typeof settings.receiver !== 'string' || !settings.receiver) {
    structure(`${path}.receiver`, 'receiver (a contact point name) is required');
  } else if (targets && !targets.receivers.includes(settings.receiver)) {
    structure(
      `${path}.receiver`,
      `contact point ${JSON.stringify(settings.receiver)} does not exist (known: ${targets.receivers.join(', ') || 'none'})`
    );
  }
  for (const field of ['groupWait', 'groupInterval', 'repeatInterval']) {
    if (settings[field] !== undefined && (parseDuration(settings[field]) ?? -1) < 0) {
      structure(`${path}.${field}`, `${field} must be a duration`);
    }
  }
  for (const field of ['muteTimeIntervals', 'activeTimeIntervals']) {
    const refs = settings[field];
    if (refs === undefined) {
      continue;
    }
    if (!Array.isArray(refs) || refs.some((ref) => typeof ref !== 'string')) {
      structure(`${path}.${field}`, `${field} must be a list of time interval names`);
      continue;
    }
    for (const ref of refs) {
      if (targets && !targets.timeIntervals.includes(ref)) {
        structure(`${path}.${field}`, `time interval ${JSON.stringify(ref)} does not exist`);
      }
    }
  }
}

const DURATION_UNITS: Record<string, number> = { ms: 0.001, s: 1, m: 60, h: 3600, d: 86400, w: 604800, y: 31536000 };

/** Seconds of a Prometheus duration such as `1h30m`, `0s`, or `90s`; undefined when invalid. */
export function parseDuration(value: unknown): number | undefined {
  if (typeof value !== 'string' || !value) {
    return undefined;
  }
  if (value === '0') {
    return 0;
  }
  const parts = [...value.matchAll(/(\d+)(ms|s|m|h|d|w|y)/g)];
  if (parts.length === 0 || parts.map((part) => part[0]).join('') !== value) {
    return undefined;
  }
  return parts.reduce((total, [, amount, unit]) => total + Number(amount) * DURATION_UNITS[unit], 0);
}

function safeParse(content: string): AnyRecord | undefined {
  try {
    return JSON.parse(content);
  } catch {
    return undefined;
  }
}

function isRecord(value: unknown): value is AnyRecord {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

function compact<T extends Record<string, unknown>>(record: T): Partial<T> {
  return Object.fromEntries(Object.entries(record).filter(([, value]) => value !== undefined)) as Partial<T>;
}
